### ISSUE TITLE
Add systemd support

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/dhtnode#78]
Systemd support should be added in 3 stages:

- [x] Create the unit file and add it to the package (when available)
- [x] Deploy the unit file (deploying the package when available)
- [ ] Switch the servers running the app to systemd

**Comment by nemanja-boric-sociomantic** [comment]
The first two items can be ticked ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
Do it!

**Comment by gavin-norman-sociomantic** [comment]
Moving to internal repo.
